[config]
schemaVersion = "0.0.1"

[package]
namespace = "Jiemas"
name = "EnlightenedJi"
versionNumber = "0.1.0"
description = "Mods Ji to be harder"
websiteUrl = "link to the git repo"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "0.0.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
